stages:
  - docker
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

  API_IMAGE_DEV: $CI_REGISTRY_IMAGE/communication-control:dev
  UI_IMAGE_DEV: $CI_REGISTRY_IMAGE/map-client:dev
  API_IMAGE_MAIN: $CI_REGISTRY_IMAGE/communication-control:main
  UI_IMAGE_MAIN: $CI_REGISTRY_IMAGE/map-client:main

default:
  image: docker:24.0.5-cli
  services:
    - name: docker:24.0.5-dind
      alias: docker

docker_dev_api:
  stage: docker
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$API_IMAGE_DEV" -f Dockerfile_API .
    - docker push "$API_IMAGE_DEV"
  only:
    - dev

docker_dev_ui:
  stage: docker
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$UI_IMAGE_DEV" -f Dockerfile_UI .
    - docker push "$UI_IMAGE_DEV"
  only:
    - dev

docker_main_api:
  stage: docker
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$API_IMAGE_MAIN" -f Dockerfile_API .
    - docker push "$API_IMAGE_MAIN"
  only:
    - main

docker_main_ui:
  stage: docker
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$UI_IMAGE_MAIN" -f Dockerfile_UI .
    - docker push "$UI_IMAGE_MAIN"
  only:
    - main